### ISSUE TITLE
Bluetooth sharing class-Connecting to another device

### ISSUE THREAD

**Issue by ValliappanValliappan** [NRG948/NRG-Scouting-Application#1]
It does not matter which device is the server i.e the server can be the laptop or the scout's tablet. 
For guidance, go to: https://developer.android.com/guide/topics/connectivity/bluetooth.html

**Comment by Once28** [comment]
Is the Robot competition in the middle of the arena? And where is the main PC located int he arena? How far can our Tablets go while still in range? And how critical does the main PC need connection to the scouts tablet?

**Comment by Knayam7** [comment]
The robotics competition will be in the middle of the gym or auditorium, with scouts located on the sides, situated on bleachers. The main PC will be used by the Head Scout, John McAvoy, who will need all the data collected. Since they are fairly cheap tablets, the BlueTooth range should be conservative, so about 5 feet. The connection from the main PC to the scouts is quite critical, as data mjust be sent for evaluation

Cheers,
Mayank

**Comment by nchhaj189** [comment]
Who is once2i

**Comment by Once28** [comment]
once2i?
