### ISSUE TITLE
The effective range to Bluetooth and Wifi compared

### ISSUE THREAD

**Issue by Once28** [NRG948/NRG-Scouting-Application#2]
Classic Bluetooth technology | Bluetooth Smart technology
                                                                                   |
 Distance/range (theoretical max.)   | 100 m (330 ft) | >100 m (>330 ft)

https://en.wikipedia.org/wiki/Bluetooth_Low_Energy 
just some info from wiki about the range to BLE.

a range of about 20 meters (66 feet) indoors and a greater range outdoors. Hotspot coverage can be as small as a single room with walls that block radio waves, or as large as many square kilometres achieved by using multiple overlapping access points.

https://en.wikipedia.org/wiki/Wi-Fi

Since its my first time, I do not know how big the tournament arena is so I was just thinking about the range of the connections.

**Comment by Knayam7** [comment]
WiFi cannot be used within 100 feet of the FRC arena, so that is off the table if you want to have data transmitted mid-competition. Once again, these are some old, cheap tablets, so I would be extremely conservative with their range. I'd say they could probably go for 5-20 ft, as they DON'T use Bluetooth 4 or 5, like the examples used there. 

Cheers,
Mayank
